services:
  lab-vuln-host:
    build:
      context: ./vulnerable-target
      dockerfile: Dockerfile
    image: unified-lab-vuln-host:latest
    container_name: lab-vuln-host
    hostname: lab-vuln-host
    restart: unless-stopped
    networks:
      lab_net:
        ipv4_address: 172.28.10.10
    volumes:
      - lab_data:/srv/labdata
    ports:
      - "2121:21"
      - "2323:23"
      - "1445:445"

networks:
  lab_net:
    name: lab_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.10.0/24

volumes:
  lab_data:
